name: ProductService CI/CD workflow

on:
  push:
    branches: [ "integration" ]
  pull_request:
    branches: [ "*" ]
    paths: [ '**/*']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step1: Checkout the code
    - uses: actions/checkout@v4

    #Step2: Setup JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    #Step3: Build the project with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 4: Run Unit Tests
    - name: Run Unit Tests
      run: mvn -B test --file pom.xml
      
    - name: Generate Code Coverage
      run: mvn jacoco:report --file pom.xml
      
    # Step 5: Run Integration Tests
    - name: Run Integration Tests
      run: mvn -B verify --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph --file pom.xml
